name: ict_ebook_hsa
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
      sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.1.2
  dots_indicator: ^3.0.0
  dio: ^5.2.1+1
  path_provider: ^2.0.15
  permission_handler: ^10.3.0
  syncfusion_flutter_pdf: ^22.2.11
  syncfusion_flutter_pdfviewer: ^22.2.11
  cached_network_image: ^3.2.3
  provider: ^6.0.5
  animated_splash_screen: ^1.3.0
  mime: ^1.0.4
  email_validator: ^2.1.17
  string_validator: ^1.0.0
  image_picker: ^1.0.0
  flutter_easyloading: ^3.0.5
  disk_space_plus: ^0.2.3
  page_transition: ^2.0.9
  video_player: ^2.7.0
  google_fonts: ^5.1.0
  chewie: ^1.7.0
  flutter_statusbarcolor_ns: ^0.5.0
  percent_indicator: ^4.2.3
  concentric_transition: ^1.0.3
  connectivity_plus: ^4.0.2
  getwidget: ^4.0.0

dev_dependencies:
  flutter_test:
      sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "img/mylogo.png"
  android: true
  ios: true
  background_color: "#FFFFFF"


  flutter_lints: ^2.0.0


flutter:

 
  uses-material-design: true

  assets:
      - img/

  fonts:
      - family: Orbitron
        fonts:
          - asset: fonts/Orbitron-Regular.ttf
          - asset: fonts/Orbitron-Bold.ttf
      - family: WorkSans
        fonts:
          - asset: fonts/WorkSans-Regular.ttf
          - asset: fonts/WorkSans-Bold.ttf
 
